# python -X utf8 train.py

data:
  target: "dataset.WrappedDataModule"
  batch_size: 64
  train:
    size: 128
    root_dir: "C:\\Users\\user\\khmoon\\assign\\dataset\\Syn_data\\train\\"
    font_dir: "C:\\Users\\user\\khmoon\\assign\\dataset\\Syn_data\\fonts\\"
    template_font: "C:\\Users\\user\\khmoon\\assign\\dataset\\Syn_data\\fonts\\Pretendard-Medium.ttf"

  validation:
    size: 128
    root_dir: "C:\\Users\\user\\khmoon\\assign\\dataset\\Syn_data\\eval\\"
    font_dir: "C:\\Users\\user\\khmoon\\assign\\dataset\\Syn_data\\fonts\\"
    template_font: "C:\\Users\\user\\khmoon\\assign\\dataset\\Syn_data\\fonts\\Pretendard-Medium.ttf"

num_workers: 32
check_freq: 1
prefetch_factor: 6
persistent_workers: True



model:
  target: trainer.StyleNet
  params:
    image_size: 128
    patch_size: 16
    in_chans: 3
    num_classes: 0
    emb_dim: 768
    ckpt_path:
    trainable: True
    lr: 5e-6
    alpha_removal: 1.0
    alpha_seg: 1.0
    alpha_color: 1.0
    alpha_font: 1.0
    enable_spatial_head: True
    enable_glyph_head: True



# load_ckpt_path: "/home/undergrad/model_base/TextCtrl-Translate/logs/lightning_logs/version_17/checkpoints/epoch=29-step=9990.ckpt"

lightning:
  log_every_n_steps: 50
  accumulate_grad_batches: 4
  precision: 16       # 또는 "16-mixed" (v1.x)
  max_epochs: 80
  accelerator: "gpu"
  devices: 1
  # strategy: ddp
  # strategy: single_device
  default_root_dir: "./logs/pre_style_logs"


imagelogger_callback:
  target: "trainer.StyleNetImageLogger"
  params:
    train_batch_frequency: 4500
    valid_batch_frequency: 2
    disable_wandb: false
    generation_kwargs:
      seed: 42
≠