model:
  target: "src.trainer.CtrlBase.ControlBase"
  params:
    control_config:
      target: "src.trainer.CtrlBase.StylePyramidNet"
      params:
        image_size: 256
        patch_size: 16
        in_channels: 3
        embed_dim: 768
        model_channels: 320
        channel_mult: [ 1, 2, 4, 4 ]
        pyramid_sizes: [ 32, 16, 8, 4]
        use_checkpoint: True


    base_config:
      noise_scheduler: "diffusers.PNDMScheduler"
      scheduler_config: "weights/sd/scheduler/scheduler_config.json"
      num_inference_steps: 50
      min_training_steps: 0

      vae:
        pretrained: "weights/sd/vae/"
        normalizer: 0.18215

      text_encoder_optimized: False
      text_encoder:
        target: "src.module.textencoder.modules.LabelEncoder"
        params:
          max_len: 24
          emb_dim: 768
          ckpt_path: "weights/text_encoder.pth"

      unet_pretrained: "weights/sd/unet/diffusion_pytorch_model.bin"
      unet:
        target: "src.trainer.CtrlBase.ControlUNetModel"
        params:
          cross_attention_dim: 768

      reconstruction_loss: True
      ocr_loss_alpha: 0.01
      cond_on_text_image: False
      font_path: "weights/arial.ttf"

      ocr_model:
        model_name_or_path: "/home/undergrad/model_base/TextCtrl-Translate/weights/trocr-ko"
        ocr_supervised: False
        optimize: false
        max_length: 256
        num_beams: 4
